### ISSUE TITLE
Check if the logout button is enabled on Android 

### ISSUE THREAD

**Issue by dianabarsan** [medic/angular10-migration#1]

**Comment by mrsarm** [comment]
I have checked the "Log out" function in Android 10 (Webview) and Android 7 (XWalk) with the latest app version and the latest version of the CHT from the Angular 10 branch, and it works as intended: it is shown only if enabled from the "Roles & permissions" view, and once enabled the menu entry works as expected.

![Log out CHT A10 on Mobile](https://user-images.githubusercontent.com/1608415/103573779-cf9d7680-4e9c-11eb-81ce-1843366e96bf.jpg)
