### ISSUE TITLE
Fix form's radio button display

### ISSUE THREAD

**Issue by latin-panda** [medic/angular10-migration#110]
Contact form's radio buttons are being display one next to each other in several places like: when reassigning a contact or when creating new health facility and selecting primary contact from new or existing person, etc.

Check the css code that overrides Enketo styles.

4750-angular-10-take-2 branch:
<img width="772" alt="Screen Shot 2021-01-05 at 5 55 08 pm" src="https://user-images.githubusercontent.com/66472237/103662909-12e20d00-4fa3-11eb-9174-67cd93fd4a9a.png">

Master (Gamma screenshot): 
<img width="733" alt="Screen Shot 2021-01-05 at 5 55 15 pm" src="https://user-images.githubusercontent.com/66472237/103663210-6e13ff80-4fa3-11eb-96f6-2e16664cb04f.png">

**Comment by dianabarsan** [comment]
Are you sure this is the same form? The text looks different so I'm inclined to think other things might be different. 

One form says "health facility" and the other form says "district".

**Comment by dianabarsan** [comment]
I'm crosschecking identical forms and the layout looks identical in both apps: 

![image](https://user-images.githubusercontent.com/35681649/104494790-97561080-55df-11eb-8c78-ab0fbb30ebcd.png)

![image](https://user-images.githubusercontent.com/35681649/104494834-aa68e080-55df-11eb-9dfc-571e16ca7468.png)

**Comment by dianabarsan** [comment]
BTW, Angular 10 is on the right (hint: missing contacts action bar and a reaaally small miss in vertical alignment in the LHS list if icon vs text).

**Comment by latin-panda** [comment]
Yes, just tested by loading another form and it loaded vertically. CSS also looks good. Closing ticket.
