### ISSUE TITLE
Investigate if we can improve grunt build overall

### ISSUE THREAD

**Issue by dianabarsan** [medic/angular10-migration#115]
This includes all steps in building the webapp (ddoc and everything). 
We currently have an issue where the production build is removing all files from its designated build folder `attachments`, so the final builds are missing translations (among other things).

**Comment by latin-panda** [comment]
Regarding angular build piece:

[This](https://angular.io/guide/aot-compiler) and [this](https://angular.io/guide/angular-compiler-options) might be worth checking out. 
I had a quick play with just `ng build --aot` and got in average 7s saving, ran it 6x each. 

<img width="1274" alt="Screen Shot 2021-01-25 at 10 43 28 am" src="https://user-images.githubusercontent.com/66472237/105659590-abf9a900-5efb-11eb-81c2-37a2f683bef8.png">

**Comment by dianabarsan** [comment]
Doesn't `-aot` simply enable the option which we already enable in the build file?

**Comment by dianabarsan** [comment]
here https://github.com/medic/cht-core/blob/4750-angular-10-take-2/webapp/angular.json#L25

**Comment by latin-panda** [comment]
Yes, exact same config, I saw it before but then I still tried to add it in the command and got 7s saving 🤷‍♀️ 
btw I saw this comment in Angular / issues / 37293 
<img width="934" alt="Screen Shot 2021-01-25 at 12 41 17 pm" src="https://user-images.githubusercontent.com/66472237/105666242-6a70fa00-5f0b-11eb-8e36-808115193d3d.png">
I tried the same approach with Angular 11 and not improvement by adding --aot in the command, maybe they fixed something.

**Comment by dianabarsan** [comment]
> Regarding angular build piece:
> 
> [This](https://angular.io/guide/aot-compiler) and [this](https://angular.io/guide/angular-compiler-options) might be worth checking out.
> I had a quick play with just `ng build --aot` and got in average 7s saving, ran it 6x each.
> 
> <img alt="Screen Shot 2021-01-25 at 10 43 28 am" width="1274" src="https://user-images.githubusercontent.com/66472237/105659590-abf9a900-5efb-11eb-81c2-37a2f683bef8.png">

Everything is quicker in your second image, including npm-ci-shared-libs which is wholly disconnected to angular. 
My guess is that your computer was under different load at build time, which produced this difference.

**Comment by latin-panda** [comment]
Yeah maybe, I ran it several times with not waiting in between.

**Comment by dianabarsan** [comment]
My goal for this issue was to try and shuffle some grunt tasks around to minimize CI runtime. 
Ideally, I could have changed it so it runs all tests and then builds all artifacts, i.e. failing early. 
However: 
- admin still needs to be built before being tested 
- api resource extraction unit test requires some default docs that only exist after everything is built
- a considerable refactor of grunt jobs was needed, because building and testing are now grouped and run under 2 compact tasks. 

So, I've cleaned up comments and todos and, as a quick win, I'm running static-analysis (eslint) before build and, at least, failing early there.
