### ISSUE TITLE
Flacky e2e test Submit Enketo form submits on reports tab

### ISSUE THREAD

**Issue by dianabarsan** [medic/angular10-migration#133]
This test sometimes fails with this error: 
```
1) Submit Enketo form submits on reports tab
  - Failed: visibilityOf failed in 10 seconds By(css selector, #reports-content .details ul li:first-child p)
  Wait timed out after 10013ms
```

![image](https://user-images.githubusercontent.com/35681649/107315256-fb64db00-6a9e-11eb-9de2-b5028838eaa7.png)

example suite: https://github.com/medic/cht-core/runs/1858217459?check_suite_focus=true

**Comment by newtewt** [comment]
I've pushed a change to use the `clickElementNative` in an attempt to fix the flakey ness. As part of this I've also been reviewing the test file the executes before. I think it(`docs-by-replication-key-view.js`) could be cleaned up a bit but I want to see if this fixes it and come back if need be.

**Comment by dianabarsan** [comment]
I've just seen this test fail on a very fresh branch, locally: 
![image](https://user-images.githubusercontent.com/35681649/108034688-8bc29300-703e-11eb-89be-9f7b68260854.png)

**Comment by dianabarsan** [comment]
I think I've found the culprit :)
