### ISSUE TITLE
Integrate tour in Analytics, Tasks and Messages tabs

### ISSUE THREAD

**Issue by latin-panda** [medic/angular10-migration#18]
Tour feature needs to be integrated in:

- [x] Message tab -> [see original](https://github.com/medic/cht-core/blob/631b63cfd671f6a1f27a10a00476af4e5fc77bc6/webapp/src/js/controllers/messages.js#L105)
- [x] Analytics tab -> [see original](https://github.com/medic/cht-core/blob/631b63cfd671f6a1f27a10a00476af4e5fc77bc6/webapp/src/js/controllers/analytics.js#L55)
- [x] Tasks tab -> [see original](https://github.com/medic/cht-core/blob/631b63cfd6/webapp/src/js/controllers/tasks.js#L57)
- [x] Once migrated all the actions in all the views, like the button that allows to edit a contact, or the one to mark a report as OK or wrong... check that the tours pointing to those components still work.

Reports and Analytics are already migrated but not merged yet, check https://github.com/medic/cht-core/pull/6713

**Comment by latin-panda** [comment]
Hi @mrsarm if you create a ticket for the tour feature, can you please link it here :) Thanks

**Comment by mrsarm** [comment]
The PR is here: https://github.com/medic/cht-core/pull/6713

Currently the tour for "Analytics" is already migrated in the PR (it only has 1 step in the tour) and rest the "Messages" and "Tasks" tabs.

**Comment by latin-panda** [comment]
@mrsarm  that's awesome!! I have assigned this one to you as it's part of your PR work, thank you!! :)

**Comment by mrsarm** [comment]
#### Update

Checking again the tour now the **"Tasks" tab** migration is completed, all the steps there are working fine in both mobile and desktop version.

Only rest to check again the **"People" tab**: the tour is mostly working in the tab but because the buttons at the button to create or edit a record are not displayed yet, I'm not sure once implemented the tour will highlight correctly the migrated buttons.

**Comment by latin-panda** [comment]
Hi @mrsarm! The action bar (create, edit, etc) for People tab just got merged 🎉 that piece is unblocked now :)

**Comment by mrsarm** [comment]
Tested again. It works well with the latest changes.
