### ISSUE TITLE
Document final version of grunt tasks for webapp

### ISSUE THREAD

**Issue by latin-panda** [medic/angular10-migration#19]
During migration we had to create and modify some grunt tasks for building the app and running unit test. 

Once the migration is almost complete and we're confident of our grunt configuration, document the final version in the readme files, cht-docs and any other necessary place.

**Comment by latin-panda** [comment]
Blocked: This is the last thing to do in the migration and after: https://github.com/medic/angular10-migration/issues/19

**Comment by dianabarsan** [comment]
@latin-panda 
I'm not sure what you meant by documenting our grunt tasks. 
The upper level grunt tasks were not changed or renamed, I believe. 
I found a single reference in https://github.com/medic/cht-core/blob/master/DEVELOPMENT.md to a renamed grunt task: `unit-continuous` was renamed to `unit-webapp-continuous`. 

Were you thinking of something else?

**Comment by latin-panda** [comment]
Yeah, I thought we would include more commands and have a command directory.
But people can see the grunt file for more understanding. I'm going to close this one.
