### ISSUE TITLE
Investigate if we can reduce bundle-size

### ISSUE THREAD

**Issue by dianabarsan** [medic/angular10-migration#39]
We've had occurrences in the past where dependencies were loaded twice (either because of different versions requirements or just because of nonexistent tree-shaking). 
Once the migration is complete, we should check if tree-shaking is working as expected, we have no performance bail-outs and our bundle is the smallest possible.

**Comment by dianabarsan** [comment]
@njogz I remember you mentioning working on this in a stand-up (and a daily), but you haven't assigned yourself or provided updates here. 
Is there any progress on this or is it free to be picked up?

**Comment by njogz** [comment]
@dianabarsan yes I looked into it briefly but left it unassigned intentionally so someone else can pick it up because I didn't make much progress on it. I tried to use `webpack-bundle-analyzer` but didn't get it working and got distracted by other work.

**Comment by dianabarsan** [comment]
Ok, thanks :)
