### ISSUE TITLE
Check all tabs for memory leaks

### ISSUE THREAD

**Issue by dianabarsan** [medic/angular10-migration#4]
We had this problem before: https://github.com/medic/cht-core/issues/5050

Please follow the reproduction steps listed here and note if there are any memory or dom node leaks: https://github.com/medic/cht-core/issues/5050#issuecomment-454686379

**Comment by dianabarsan** [comment]
I was testing if some new jquery datepickers that I had migrated were generating dom node leaks. 
Comparing heap snapshots, it looked like *everything* was leaking dom nodes! 

Turns out, Chrome has a ~bug~ feature where devtools keeps references of removed dom nodes that had event listeners attached. 
See: 
https://github.com/angular/angular/issues/35575 
https://bugs.chromium.org/p/v8/issues/detail?id=10297

**Comment by latin-panda** [comment]
Blocked: Until performance improvement work is merged.
