### ISSUE TITLE
Migrate "contacts" tasks actions

### ISSUE THREAD

**Issue by dianabarsan** [medic/angular10-migration#51]
Original issue that adds this feature: https://github.com/medic/cht-core/issues/1505

**Comment by latin-panda** [comment]
This ticket is about:
> The required [contacts paths + add ](https://github.com/medic/cht-core/blob/4750-angular-10-take-2/webapp/src/ts/modules/tasks/tasks-content.component.ts#L272)to be functional to know correct links and actually test
