### ISSUE TITLE
Finish migrating app-component (inbox)

### ISSUE THREAD

**Issue by latin-panda** [medic/angular10-migration#92]
Finish migrating related code to the start of the application that doesn't belong to specific modules, like the one in app-component.
Verify all those are working as expected and migrate/increase unit test where needed. 

- [Bootstrap-layer ](https://github.com/medic/cht-core/blob/2c74a6e25428f18c7f41bd80880cbe789953f6a9/webapp/src/templates/inbox.html#L17) used [here](https://github.com/medic/cht-core/blob/master/webapp/src/js/bootstrapper/index.js)
- The performance code in [inbox.html](https://github.com/medic/cht-core/blob/2c74a6e25428f18c7f41bd80880cbe789953f6a9/webapp/src/templates/inbox.html#L8) Do we need it?
- Migrate or clean the commented code in [main.ts](https://github.com/medic/cht-core/blob/4750-angular-10-take-2/webapp/src/ts/main.ts)
- Migrate and clean the commented code in [app-component](https://github.com/medic/cht-core/blob/4750-angular-10-take-2/webapp/src/ts/app.component.ts) 
- Since app component doesn't run ng-destroy then see what to do with [DB Closed Modal](https://github.com/medic/cht-core/blob/4750-angular-10-take-2/webapp/src/templates/modals/database_closed.html) in [app-component](https://github.com/medic/cht-core/blob/d8c7435c3ee760ddec550427cf7bc7471c1fa04c/webapp/src/ts/app.component.ts#L749)
- See if there's something else pending :)

**Comment by dianabarsan** [comment]
Assigning myself because I had already included this in one of my branches.
